# Unique name for PMD Workflow
name: Salesforce APEX code analyzer

# Definition when the workflow should run
on:
  pull_request:
      branches: ['**']
      types: [opened, synchronize, reopened, ready_for_review]
      paths:
        - "force-app/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    apex-test:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
          - name: Checkout source code
            uses: actions/checkout@v1
          - name: Check APEX
            uses: legetz/setup-pmd@v6.38
          - run: pmd -language apex -dir . -rulesets ./pmd-rules.xml -f text
