# Unique name for PMD Workflow
name: Salesforce APEX code analyzer

# Definition when the workflow should run
on:
  pull_request:
      branches: ['**']
      types: [opened, synchronize, reopened, ready_for_review]
      paths:
        - "force-app/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    apex-code-analizer:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
          - name: Checkout source code
            uses: actions/checkout@v1
          - name: Download a PMD ruleset
            id: download-poetry
            with:
              file-url: 'https://github.com/ChuckJonas/vscode-apex-pmd/blob/master/rulesets/apex_ruleset.xml'
              file-name: 'pmd-rules.xml'
              location: '.'
          - name: Print the file path
            run: echo "The file was downloaded to ${{ steps.download-poetry.outputs.file-path }}"
          - name: Check APEX
            uses: legetz/setup-pmd@v6.38
          - run: pmd -language apex -dir . -rulesets ./pmd-rules.xml -f text
