#Unique name for Unit Tests Workflow
name: Apex unit tests

#Definition when the workflow should run
on:
  pull_request:
      branches: ['release-candidate/*']
      types: [opened, synchronize, reopened, ready_for_review]
      paths:
        - "force-app/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    apex-test:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
          - name: Install sfdx client
            uses: sfdx-actions/setup-sfdx@v1
          - name: Checkout source code
            uses: actions/checkout@v1
          - name: Authorize Salesforce org
            uses: sfdx-actions/setup-sfdx@v1
            with:
              sfdx-auth-url: ${{ secrets.SALESFORCE_DEPLOYMENT_ORG_SECRECT }}
          - name: Deploy source code
            run: sfdx force:source:deploy -p force-app
          - name: Run apex tests
            run: sfdx force:apex:test:run -c -r human --wait 45
